title: Hao Wang
description: Political Science, Statistical Analysis

url: http://haowang666.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Research
   url: /research
 - title: 中文
   url：／chinese
social:
   github: haowang666
   email: haowang@asu.edu

google_analytics: "UA-58263416-1"
