title: Hao Wang
description: Political Science, Statistical Analysis

url: http://haowang666.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

mathjax: true

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Research
   url: /research
 - title: Computing
   url: /tools  
 - title: Contact
   url: /contact

   
social:
   github: haowang666
   email: haowang@asu.edu

google_analytics: "UA-93677601-1"
